### ISSUE TITLE
是否考虑使用routing-mark替代uid以解决clash回环的问题？

### ISSUE THREAD

**Issue by srk24** [mritd/tpclash#1]
https://github.com/Dreamacro/clash/pull/1705
https://github.com/Dreamacro/clash/wiki/configuration

linux环境下其实直接使用routing-mark，也许这是不错的选择，这样就避免了创建新用户了

**Comment by mritd** [comment]
😯 我刚刚才知道又这个功能, 这两天研究一下; 还有 tun 的版本也在研究中, 后续准备增加本地代理开关, 防止搞坏

**Comment by zou2699** [comment]
用这个一键安装也不错，https://github.com/Kr328/clash-premium-installer

**Comment by mritd** [comment]
我看了下 routing-mark 相关的 PR, 总体上来说似乎使用 routing-mark 来排除 clash 自身流量不是特别好的操作:

- 1、routing-mark 本身设计为多个 Proxy Group 出口流量做策略路由
- 2、tpclash 想要通过 routing-mark  排除 clash 自身流量则需要 **在路由表中为所有 routing-mark 流量指定路由**
- 3、routing-mark 本身是留给用户做自己的策略出口的, tpclash 如果无脑把 mark 的流量都给处理了那么相当于覆盖其本身设计行为

不知道我的理解对不对 XD

**Comment by mritd** [comment]
目前还不太确定这个 routing-mark 在 tun 模式中是否可行

**Comment by srk24** [comment]
我尝试去理解你的思路，但是没有搞懂。
我的理解是：clash可以对指定group流量mark，也可以对所有出口流量mark，然后需要对nat表的output（指已被clash mark的流量）进行路由即可

**Comment by mritd** [comment]
这个理解没问题，不过回到 tpclash 的问题上

- 我们的需求是排除 clash 自身流量防止死循环。
- routing mark 是让用户自己做路由用的(比如多网卡情况下指定某个 group 流量走联通线路)

我们可以做到的是读取所有 mark 配置，然后为这些 mark 配置路由，但是如果用户想自己手动控制就很可能和我们的路由冲突。

我考虑的核心点是这个 mark 标记本身是留给用户的，我强行拿过来给用了会不会出问题😂😂😂。

**Comment by srk24** [comment]
新版本似乎修复了routing-mark

**Comment by srk24** [comment]
我尝试去理解你的思路，但是没有搞懂。
我的理解是：clash可以对指定group流量mark，也可以对所有出口流量mark，然后需要对nat表的output（指已被clash mark的流量）进行路由即可
