### ISSUE TITLE
大佬考虑支持nftables吗？

### ISSUE THREAD

**Issue by cw2023** [mritd/tpclash#11]
如题，希望大佬考虑一下

**Comment by mritd** [comment]
这是下一步的计划, 目前已经完全切换到 tun 模式, 依赖的 iptables 其实很少; 后面打算完全删除 iptables 相关代码, 因为目前主流系统 iptables 也是做的前端包装. 如果可能后面会不采用 cmd exec 的方式去处理 nftables, 并消除所有 iptables 调用.
