### ISSUE TITLE
请问主路由能用这个配置透明代理吗

### ISSUE THREAD

**Issue by ayanami-desu** [mritd/tpclash#13]
您所述的似乎是在旁路由上部署透明代理的方法

**Comment by mritd** [comment]
理论可以, 但是不推荐. 我个人的一点偏执思想: 透明代理服务都是不稳定的, 在主路由操作如果代理服务器出问题或者配置出问题很可能导致断网.

**Comment by Wrandz** [comment]
@mritd 你好，我借楼问一下，为啥在说明文档中注明不要把dns设置为tpclash，tun配置里面不是已经劫持了所有53端口的流量，应该是可以的吧

**Comment by mritd** [comment]
@Wrandz 以前是通过 iptables 做的劫持, 现在是 tun 劫持; 无论怎样, 简单的说就是:

**劫持是指劫持通过本机中转的流量(forward)**, 而不是处理发送到本机的流量; 

所以如果你把 DNS 直接指向过来, 那么很可能是在一些规则处理时, 判定该请求发往 tpclash 这台机器自身, 劫持就可能被跳过.

- 1、假设 A 的流量需要发往 C: A ---> C
- 2、A 把网关设置成 B, 那么流量路径就是: A ----> B ----> C
- 3、此时在 B 上可以劫持 A 发往 C 的流量
- 4、如果 A 直接向 B 发送流量: A ----> B
- 5、此时 B 上的处理程序不会认为这个流量需要 "劫持", 因为发给自己的自己再劫持就多此一举

**Comment by Wrandz** [comment]
@mritd 谢谢解答。不过我很好奇，是什么样子的规则，会导致本来A ----> B ----> C的流量变成A ----> B呢？

**Comment by ZhelinCheng** [comment]
> @Wrandz 以前是通过 iptables 做的劫持, 现在是 tun 劫持; 无论怎样, 简单的说就是:
> 
> **劫持是指劫持通过本机中转的流量(forward)**, 而不是处理发送到本机的流量;
> 
> 所以如果你把 DNS 直接指向过来, 那么很可能是在一些规则处理时, 判定该请求发往 tpclash 这台机器自身, 劫持就可能被跳过.
> 
> * 1、假设 A 的流量需要发往 C: A ---> C
> * 2、A 把网关设置成 B, 那么流量路径就是: A ----> B ----> C
> * 3、此时在 B 上可以劫持 A 发往 C 的流量
> * 4、如果 A 直接向 B 发送流量: A ----> B
> * 5、此时 B 上的处理程序不会认为这个流量需要 "劫持", 因为发给自己的自己再劫持就多此一举

@mritd 大佬，按照你的说法，那AdGuardHome是可以跟tpclash在同一个系统里，并且不需要做任何处理？

**Comment by mritd** [comment]
@ZhelinCheng 大师不要放在同一个内核的主机上, 因为 tpclash 会劫持流量导致 ADG 出现问题
