### ISSUE TITLE
远程配置首次启动时不会下载

### ISSUE THREAD

**Issue by damonto** [mritd/tpclash#18]
查看源代码发现如果设置的配置文件为远程文件 tpclash 会首先删除本地的 clash 文件，但是并不会立即下载远程的 clash 文件。期望应当设置远程配置文件后立即下载一次，然后在后续定时更新。

现在这样会导致需要等待第一次 timer 的定时器时间到了过后才会启动。

**Comment by mritd** [comment]
远程配置正在加强, 最近会进行完善

**Comment by mritd** [comment]
目前期望的最终目标是完全远程托管, 比如一个 gist 配置可以让每个 node 自动更新.

**Comment by cw2023** [comment]
直接用clash自带的proxy-providers/rule-providers功能不好吗？

**Comment by mritd** [comment]
@damonto 目前已经重构了配置文件的加载逻辑, 同时加入了一个 FuncsMap, 后面可以支持更多的参数自动识别和替换; 比如目前的 接口名称 可以使用 `{{IfName}}` 占位符实现自动替换.

**Comment by damonto** [comment]
@mritd 目前最新的版本不会处理 DNS 请求了，这样就不能用 clash 的按域名分流了。
![PixelSnap 2023-06-23 at 16 03 08@2x](https://github.com/mritd/tpclash/assets/9162521/4c07730e-c2e1-489e-b07c-fb0a4c3b1333)

**Comment by mritd** [comment]
@damonto 没太懂啥意思... 我理解只要不取消 dns 的 fake ip 应该就没问题; 有相关的 changelog 么?

**Comment by mritd** [comment]
我只遇到过单纯的 tun 模式有时候本机流量 dns 劫持出现问题, 配合开启 ebpf 就好了.
