### ISSUE TITLE
clash文件下载路径调整

### ISSUE THREAD

**Issue by ysicing** [mritd/tpclash#23]
github的可能不是最新版本，可以从s3上下载 https://release.dreamacro.workers.dev/latest/clash-linux-amd64-latest.gz

github是积攒较多时才会发布新版本，s3上的会追新一些

**Comment by mritd** [comment]
但是这个没有办法拿到具体的版本号信息吧?

**Comment by ysicing** [comment]
这个确实有些，版本号还是这个github这个 `2023.05.29-17-g94c65bd`
