### ISSUE TITLE
请问dns怎么设置比较好

### ISSUE THREAD

**Issue by ntzhrm** [mritd/tpclash#24]
设置阿里dns发现好多网址不解析，设置谷歌dns发现好多国内不解析。看到新版加了dns func功能，请问怎么用

**Comment by mritd** [comment]
`dns func` 是为了让 tpclash 能够正确跟随系统上游  DNS; 

- 1、在某些内网环境下特定的域名由内部 DNS  解析
- 2、clash 配置中允许填写特定的上游 DNS
- 3、配合远程配置加载的情况下, 可能不同环境多台设备的内网 DNS 不相同
- 4、参考 [example.yaml](https://github.com/mritd/tpclash/blob/master/example.yaml#L108) 配置方式可以实现让多台位于不同内网的 tpclash 自动为 clash 设置默认的上游 DNS(通过解析 resolv.conf)

**Comment by mritd** [comment]
理论上, 你只需要在 `nameserver` 部分设置一个或多个国内的 DNS 服务器即可, clash DNS 工作的基本逻辑:

- 1、其他设备访问 example.com 前先向  clash 发送 DNS 查询请求
- 2、clash 不会进行立即查询而是直接返回 fake-ip
- 3、其他设备与 clash 建立链接
- 4、clash 通过规则引擎查找, 如果规则匹配为需要走特定代理服务器, 则不进行 DNS 解析, 直接将域名请求发送到代理服务器, 由代理服务器进行解析
- 5、如果规则中匹配到直接链接(DIRECT), 则根据 `nameserver` 进行 DSN 解析并将请求转发到解析到的 IP

需要注意的是, clash 规则是按顺序执行的, 没记错的话, 如果你的 `IP-CIDR` 类规则在域名规则上面, 可能会造成解析泄漏:

```yaml
IP-CIDR, 1.2.3.4/24, DIRECT
DOMAIN, example.com, PROXY
```
存在这种规则时, 由于你的 IP 类规则在上面, 所以 clash 为了确认你这个域名对应的 IP 是否匹配这个 `IP-CIDR`, 则 clash 可能会先在本地进行解析; **具体的规则情况你可以参考下 clash 文档, 这个顺序是不是这样我不太确定, 但是会有这种情况存在.**

**Comment by mritd** [comment]
核心思路就是: 保证你需要走代理的域名, 有特定的域名规则为他进行分流; 这样解析行为是应该发生在代理服务器上而不是本地的; 如果规则配置出现问题会导致一些需要代理的域名 DNS 解析发生在本地, 会有 DNS 污染等问题.

**Comment by ntzhrm** [comment]
Good
