### ISSUE TITLE
谁能帮看下，为什么分流不成功？

### ISSUE THREAD

**Issue by luzhaohui** [mritd/tpclash#25]
做旁路由使用，在新的 Debian 11 上运行，没有其他干扰，用命令行启动 ./tpclash -c /etc/clash.yaml 能正常运行，但是disney/netflix/openai/paypal 无法分流。谁能帮看看配置文件有什么问题吗？

`
#port: 7890
#socks-port: 7891
redir-port: 7892
tproxy-port: 7893
#mixed-port: 7890

allow-lan: true

bind-address: '*'

mode: rule

log-level: info #warning

ipv6: false

external-controller: 0.0.0.0:9090
external-ui: yacd
secret: 

interface-name: eth0

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  auto-redir: true
  auto-detect-interface: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  default-nameserver:
    - 192.168.0.5
    - 192.168.0.6
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
  nameserver:
    - 192.168.0.5
    - 192.168.0.6

proxies:
  - name: "HK|1.0x|CC"
    type: ss
    server: xxx.xxx.xxx.xxx
    port: xxxxx
    cipher: aes-128-gcm
    password: "password"

  - name: "HK1|1.0x|IPLC"
    type: ss
    server: xxx.xxx.xxx.xxx
    port: xxxxx
    cipher: aes-128-gcm
    password: "password"

  - name: "HK2|1.0x|IPLC"
    type: ss
    server: xxx.xxx.xxx.xxx
    port: xxxxx
    cipher: aes-128-gcm
    password: "password"

  - name: "SG|1.0x|IPLC"
    type: ss
    server: xxx.xxx.xxx.xxx
    port: xxxxx
    cipher: aes-128-gcm
    password: "password"

  - name: "US|1.0x|OCI"
    type: ss
    server: xxx.xxx.xxx.xxx
    port: xxxxx
    cipher: aes-128-gcm
    password: "password"

  - name: "US|1.0x|RN"
    type: ss
    server: xxx.xxx.xxx.xxx
    port: xxxxx
    cipher: aes-128-gcm
    password: "password"

proxy-groups:
  - name: "Hongkong"
    type: fallback
    proxies:
      - HK|1.0x|CC
      - HK1|1.0x|IPLC
      - HK2|1.0x|IPLC
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  - name: "Singapore"
    type: url-test
    proxies:
      - SG|1.0x|IPLC
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  - name: "US"
    type: fallback
    proxies:
      - US|1.0x|RN
      - US|1.0x|OCI
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

rules:
  - RULE-SET,disney,Singapore
  - RULE-SET,netflix,Singapore
  - RULE-SET,openai,Singapore
  - RULE-SET,paypal,US
  - MATCH,Hongkong

rule-providers:
  disney:
    type: http
    behavior: "classical"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml"
    path: ./ruleset/disney.yaml
    interval: 86400

  netflix:
    type: http
    behavior: "classical"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml"
    path: ./ruleset/netflix.yaml
    interval: 86400

  openai:
    type: http
    behavior: "classical"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml"
    path: ./ruleset/openai.yaml
    interval: 86400

  paypal:
    type: http
    behavior: "classical"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.yaml"
    path: ./ruleset/paypal.yaml
    interval: 86400

`

**Comment by mritd** [comment]
可以提供下 访问目标网站时 tpclash 的日志么?

**Comment by luzhaohui** [comment]
> 可以提供下 访问目标网站时 tpclash 的日志么?

其实我大概是搞明白了，做旁路由，从 ROS 把国外流量分流到 tpclash，并不会在 tpclash 里进行 DNS 解析，而分流规则基本是根据域名进行分流的，所以不会匹配分流规则，最后都到 MATCH 兜底了。

**Comment by mritd** [comment]
意思是 ROS 预解析了? 然后到 clash 这里全是 IP target?

**Comment by luzhaohui** [comment]
> 意思是 ROS 预解析了? 然后到 clash 这里全是 IP target?

是的，已经确认了，作为旁路由使用，如果主路由已经完成了国内外IP分流，是不会匹配 tpclash 里配置的域名规则的。
我用 [https://github.com/QiuSimons/Netflix_IP](url) 的数据改写成 IP-CIDR 规则，成功分流 Netflix。

  # Netflix
  - IP-CIDR,8.41.4.0/24,Singapore
  - IP-CIDR,23.23.189.144/28,Singapore
  - IP-CIDR,23.246.0.0/18,Singapore
  - IP-CIDR,34.195.253.0/25,Singapore
  - IP-CIDR,34.210.42.111/32,Singapore
  - IP-CIDR,37.77.184.0/21,Singapore
  - IP-CIDR,38.72.126.0/24,Singapore
  - IP-CIDR,45.57.0.0/17,Singapore
  - IP-CIDR,52.24.178.0/24,Singapore
  - IP-CIDR,52.35.140.0/24,Singapore
  - IP-CIDR,52.89.124.203/32,Singapore
  - IP-CIDR,54.148.37.5/32,Singapore
  - IP-CIDR,54.204.25.0/28,Singapore
  - IP-CIDR,54.213.167.0/24,Singapore
  - IP-CIDR,64.120.128.0/17,Singapore
  - IP-CIDR,66.197.128.0/17,Singapore
  - IP-CIDR,69.53.224.0/19,Singapore
  - IP-CIDR,103.87.204.0/22,Singapore
  - IP-CIDR,108.175.32.0/20,Singapore
  - IP-CIDR,185.2.220.0/22,Singapore
  - IP-CIDR,185.9.188.0/22,Singapore
  - IP-CIDR,192.173.64.0/18,Singapore
  - IP-CIDR,198.38.96.0/19,Singapore
  - IP-CIDR,198.45.48.0/20,Singapore
  - IP-CIDR,203.75.84.0/24,Singapore
  - IP-CIDR,203.198.13.0/24,Singapore
  - IP-CIDR,203.198.80.0/24,Singapore
  - IP-CIDR,207.45.72.0/22,Singapore
  - IP-CIDR,208.75.76.0/22,Singapore
  - IP-CIDR,210.0.153.0/24,Singapore

**Comment by mritd** [comment]
好吧... 不过我总觉得你这个预解析 需要抗污染 DNS 吧, 要不然遇到被污染的域名 给你个 127.0.0.1 不是尴尬了

**Comment by luzhaohui** [comment]
> 好吧... 不过我总觉得你这个预解析 需要抗污染 DNS 吧, 要不然遇到被污染的域名 给你个 127.0.0.1 不是尴尬了

当然，我自己用 mosdns 搭建的，抗污染没问题的。

**Comment by luzhaohui** [comment]
这个问题可以关闭了，用 Meta，开启 sniff 即可。
