### ISSUE TITLE
关于默认路径

### ISSUE THREAD

**Issue by ghost** [mritd/tpclash#3]
可否遵循官方的默认路径？
比如：
home：~/.config/clash
profile: ~/.config/clash/config.yaml
routing-mark: 6666

另外能否增加以下功能：
install 参数，用于tpclash.service
url 参数，用于下载配置文件

真正做到一行命令解决。

**Comment by mritd** [comment]
配置文件没有基于 clash 的原因是因为考虑到 tpclash 是作为透明代理网关存在的, 所以它的位置不应该是针对单用户的; 故选择使用 `/etc` 作为配置存储位置, 同时选择 `/data` 作为数据存储位置;

systemd 的 service 其实我在考虑要怎么弄, 直接写入系统目录可能不适用于某些 非 systemd 管理的系统.
