### ISSUE TITLE
在ESXI使用OVA加载，网关指向tpclash后仅支持国内网站访问

### ISSUE THREAD

**Issue by ansongd** [mritd/tpclash#31]
flatcar.butane.yaml文件仅修改以下3处：

```
 [Address]
Address=10.10.10.251/24

[Route]
Destination=0.0.0.0/0
Gateway=10.10.10.253

--config https://example.com/clash.yaml
```

成功开启后指向10.10.10.251的网关地址可以正常访问，国外网站无法访问。

请教以下：
1 ）如何使用ssh进入系统排查问题，使用ssh root登录提示密码错误
2 ）有没有其他排障手段，访问10.10.10.251:3000地址无效

**Comment by mritd** [comment]
root 密码 默认是 tpclash, 你可以进去看看

**Comment by ansongd** [comment]
好的，用root帐号调试，定位是配置文件问题，已解决
