### ISSUE TITLE
是否在内网能搭配AdGuardHome使用

### ISSUE THREAD

**Issue by ZhelinCheng** [mritd/tpclash#39]
我把Clash服务跑在10.0.0.2
AdGuardHome跑在10.0.0.6

看了大佬的文档知道如果建立一个内网的DNS是没办法正确解析的：
**如果你的被代理机器设置的 DNS 为内网地址, auto-route 是不工作的.**

但有些服务做了DNS重写，改hosts只能电脑有用，不知道大佬有没有思路或者一些方案，我可以尝试

**Comment by mritd** [comment]
我的理解 ADG 会内置一些规则, 如果是广告域名, ADG DNS 会直接拒绝; 所以你可以保持原有的架构不变, **将 Clash 的上游 DNS 设置为 ADG DNS**; 这样客户端的 DNS 仍然被 Clash 拦截并返回 fake-ip, 但是 clash 如果需要进行真实查询时会将请求转发到 ADG 从而实现拦截; **但是如果目标域名已经被代理规则匹配, 则 ADG 是不会收到 DNS 请求的.**
