### ISSUE TITLE
可以支持下 Clash.Meta 吗

### ISSUE THREAD

**Issue by ghost** [mritd/tpclash#4]
https://github.com/MetaCubeX/Clash.Meta/tree/Meta
https://clashmeta.gitbook.io/meta/
此分支支持 GeoIP 和 GeoSite ，不需要下载那么多规则文件了，改规则也很方便了。

**Comment by ben-august** [comment]
+1

**Comment by mritd** [comment]
正在考虑, 最近在尝试 Premium 版本的 ebpf 模式来兼容 docker 等工具, 也在测试 arp 攻击自动流量劫持.

**Comment by mritd** [comment]
@ghost @shallbytwo `v0.0.16` 版本已支持 Clash Meta.
