### ISSUE TITLE
不支持的 meta 规则

### ISSUE THREAD

**Issue by cshijiel** [mritd/tpclash#42]
加入规则后
- AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOSITE,cn))),REJECT

启动报错：
FTL [Config] parse config failed error=rules[3] [AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOSITE,cn))),REJECT] error: proxy [(DST-PORT] not found

**Comment by mritd** [comment]
tpclash 不会自行处理规则, 该错误为对应的 clash 核心的错误, 请向核心对应仓库报告 bug; 您可以通过以下方式获取到 clash 相关信息:

- `tpclash --version`: 获取当前使用的 clash 类型和版本号
- 启动时会打印 `INFO [main] running cmds: ...` 日志, 该日志包含完整启动命令(可不依托 tpclash 启动)
- 从 `/data/clash/xclash.yaml` 文件中获取到当前 clash 使用的配置文件
