### ISSUE TITLE
go-task 编译卡住 有没有成品二进制

### ISSUE THREAD

**Issue by dnslin** [mritd/tpclash#6]
task: [build-premium-dashboard] (cd build/yacd && yarn install > /dev/null 2>&1 && yarn build > /dev/null 2>&1)

**Comment by mritd** [comment]
你可以尝试删除 `> /dev/null 2>&1`, 这条命令是在编译 dashboard, yarn 编译时间可能稍长而且会涉及到 包下载; 推荐在有代理的环境下编译.

**Comment by dnslin** [comment]
> 你可以尝试删除 `> /dev/null 2>&1`, 这条命令是在编译 dashboard, yarn 编译时间可能稍长而且会涉及到 包下载; 推荐在有代理的环境下编译.

感谢
