### ISSUE TITLE
配合机场订阅

### ISSUE THREAD

**Issue by fpfeng** [mritd/tpclash#7]
我是机场用户，现在是下载订阅yaml文件到本地然后手动编辑加入`TProxy 模式配置`再启动tpclash
请问能否添加功能达到：用户指定命令行模式后，加载yaml后自动加入上面的配置再运行？而且应该要覆盖yaml里面的配置，因为已经看到机场有dns相关配置
当然也有可能我现在用错了，谢谢

**Comment by mritd** [comment]
目前还没有去考虑机场配置的问题, tpclash 目前的目标是专注于透明代理的管理;

其实关于机场订阅配置来说, 大部分代理程序核心程序中并没有做相关处理, 通常都是由图形化客户端帮助用户处理的; 或者换句话说关于订阅一直没有一个统一的规范和可标准化的东西, 所以 tpclash 暂时不会去过多的加入对机场配置的管理功能.

**当然目前并不是没有解决方案, 你可以尝试使用 [subconverter](https://github.com/tindy2013/subconverter/blob/master/README-cn.md) 然后通过定时任务定期更新合并你的机场配置.**

后续 tpclash 的重点改进会专注于从 iptables 切换到 nftables, 当所有核心功能稳定以后才会考虑边缘化的定制需求.

**Comment by fpfeng** [comment]
用[yq](https://github.com/mikefarah/yq)达到目的了
```shell
yq 'del(.socks-port)' airport_sub.yaml  | yq 'del(.port)' > new_airport_sub.yaml
yq ea '. as $item ireduce ({}; . * $item )' my_tpclash_config.yaml new_airport_sub.yaml > tpclash.yaml
```

**Comment by mritd** [comment]
@fpfeng v0.0.19 版本已支持远程下载配置, 可以配合 [subconverter](https://github.com/tindy2013/subconverter) 实现机场订阅转换、拉取、加载.

**Comment by fpfeng** [comment]
> @fpfeng v0.0.19 版本已支持远程下载配置, 可以配合 [subconverter](https://github.com/tindy2013/subconverter) 实现机场订阅转换、拉取、加载.

好的，点赞
